version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10@sha256:e78c46cbda5ab977b868c204c4d86ec09301085fc3c4df03e82874c8b5b8b8fe
    working_directory: /go/src/github.com/sam-myers/santorini
    steps:
      - checkout
      - run: go build
      - run: go test -v ./...
