version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/sam-myers/santorini
    steps:
      - checkout
      - run: go build
      - run: go test -v ./...
