version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10@sha256:1d900f6dd3fa533dfa1526ab920742141df9b19463aea000717b08ebf44d2b1e
    working_directory: /go/src/github.com/sam-myers/santorini
    steps:
      - checkout
      - run: go build
      - run: go test -v ./...
