version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11@sha256:07e282ae4997ac4bdd181b04b8976325715c6015c45eced2e7937508654b4a67
    working_directory: /go/src/github.com/sam-myers/santorini
    steps:
      - checkout
      - run: go build
      - run: go test -v ./...
