version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10@sha256:8c554f3346d14c56f0f674b2102682004fa1c1f57d6b6b17ea0e856bac3b643b
    working_directory: /go/src/github.com/sam-myers/santorini
    steps:
      - checkout
      - run: go build
      - run: go test -v ./...
