version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10@sha256:95e8385d2655735aab9f51565b9cb84587d397ecfe1ef6cfef4cabd169cfbf5e
    working_directory: /go/src/github.com/sam-myers/santorini
    steps:
      - checkout
      - run: go build
      - run: go test -v ./...
